Geometrix_Consensus/Geometrix_Consensus/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Geometrix_Consensus.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            ViewData["SubTitle"] = "Bienvenidos al Sistema de Produccion";
            ViewData["Message"] = "En esta aplicacion usted podra ingresar la produccion diaria y consultar los informes de Produccion";
            ViewData["Fecha"] = DateTime.Now;
            ViewData["Version"] = "20201228V2";

            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Geometrix_Consensus/Geometrix_Consensus/Controllers/InformeController.cs
using Geometrix_Consensus.Views.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Geometrix_Consensus.Controllers
{
    public class InformeController : Controller
    {
        decimal por_costo = 60, por_ganancia = 40;
        public ActionResult Index()
        {

            ViewData["SubTitle"] = "Produccion Diaria";

            List<SetFiguras> setFiguras = new List<SetFiguras>();

            SetFiguras setfigura1 = new SetFiguras();
            setfigura1.ID = 1;
            setfigura1.Cuadrado = 2;
            setfigura1.Rectangulo = 1;
            setfigura1.Triangulo = 0;
            setfigura1.Circulo = 1;
            setfigura1.ValorizadoCuadrado = 20;
            setfigura1.ValorizadoRectangulo = 11;
            setfigura1.ValorizadoTriangulo = 0;
            setfigura1.ValorizadoCiruculo = 14;
            setfigura1.Total_Set = 40;
            setFiguras.Add(setfigura1);

            SetFiguras setfigura2 = new SetFiguras();
            setfigura2.ID = 2;
            setfigura2.Cuadrado = 1;
            setfigura2.Rectangulo = 0;
            setfigura2.Triangulo = 0;
            setfigura2.Circulo = 3;
            setfigura2.ValorizadoCuadrado = 10;
            setfigura2.ValorizadoRectangulo = 0;
            setfigura2.ValorizadoTriangulo = 0;
            setfigura2.ValorizadoCiruculo = 43;
            setfigura2.Total_Set = 53;
            setFiguras.Add(setfigura2);

            SetFiguras setfigura3 = new SetFiguras();
            setfigura3.ID = 3;
            setfigura3.Cuadrado = 0;
            setfigura3.Rectangulo = 0;
            setfigura3.Triangulo = 4;
            setfigura3.Circulo = 0;
            setfigura3.ValorizadoCuadrado = 0;
            setfigura3.ValorizadoRectangulo = 0;
            setfigura3.ValorizadoTriangulo = 48;
            setfigura3.ValorizadoCiruculo = 0;
            setfigura3.Total_Set = 48;
            setFiguras.Add(setfigura3);

            SetFiguras setfigura4 = new SetFiguras();
            setfigura4.ID = 4;
            setfigura4.Cuadrado = 1;
            setfigura4.Rectangulo = 1;
            setfigura4.Triangulo = 1;
            setfigura4.Circulo = 1;
            setfigura4.ValorizadoCuadrado = 10;
            setfigura4.ValorizadoRectangulo = 11;
            setfigura4.ValorizadoTriangulo = 12;
            setfigura4.ValorizadoCiruculo = 14;
            setfigura4.Total_Set = 47;
            setFiguras.Add(setfigura4);

            ViewBag.Cant_Rectangulo = setFiguras.Sum(q => q.Rectangulo);
            ViewBag.Cant_Cuadrado = setFiguras.Sum(q => q.Cuadrado);
            ViewBag.Cant_Triangulo = setFiguras.Sum(q => q.Triangulo);
            ViewBag.Cant_Circulo = setFiguras.Sum(q => q.Circulo);

            decimal total_costo, ganancia_percibida, precio_total;

            total_costo = setFiguras.Sum(q => q.Total_Set);
            ganancia_percibida = (por_ganancia * total_costo) / por_costo;
            precio_total = total_costo + ganancia_percibida;

            ViewBag.Total_Cantidad_Set = setFiguras.Count();
            ViewBag.Total_Costo = decimal.Round(total_costo, 2); 
            ViewBag.Ganancia_Percibida = decimal.Round(ganancia_percibida, 2); 
            ViewBag.Precio_Total = decimal.Round(precio_total, 2); 

            return View(setFiguras);
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Geometrix_Consensus/Geometrix_Consensus/Controllers/ProductionController.cs
using Geometrix_Consensus.Views.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Geometrix_Consensus.Controllers
{
    public class ProductionController : Controller
    {
        public ActionResult Index()
        {
            ViewData["SubTitle"] = "Generar Produccion";

            List<Figuras> figuras = new List<Figuras>();

            Figuras figura1 = new Figuras();
            figura1.Descripcion = "Rectangulo";
            figura1.ID = 1;
            figuras.Add(figura1);
            Figuras figura2 = new Figuras();
            figura2.Descripcion = "Circulo";
            figura2.ID = 2;
            figuras.Add(figura2);
            Figuras figura3 = new Figuras();
            figura3.Descripcion = "Cuadrado";
            figura3.ID = 3;
            figuras.Add(figura3);
            Figuras figura4 = new Figuras();
            figura4.Descripcion = "Triangulo";
            figura4.ID = 4;
            figuras.Add(figura4);

            return View(figuras);
        }
        
        public ActionResult AddProduction(IList<Figuras> itm)
        {
            string fecha = Request.Form["example-date-input"];
            if (itm != null)
            {
                foreach (Figuras i in itm)
                {
                    if (i.cantidad > 0)
                    {
                        String aux = i.Descripcion;
                    }
                }
            }
            return RedirectToAction("Index", "Home");
        }
        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Geometrix_Consensus/Geometrix_Consensus/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Pagina de Inicio";
}

<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-lg-12">
            <div class="text-center m-t-lg">
                <img alt="image" class="img-rounded" src="~/Images/logo.png" style=" height: 250px; width: 300px; " />
            </div>
            <div class="text-center m-t-lg">
                <h1>
                    @ViewData["SubTitle"]
                </h1>
                <small>@ViewData["Message"]</small>
                <br />
                <small>@ViewData["Fecha"]</small>
                <br>
                <small>Version  : @ViewData["Version"]</small>
                <br>
            </div>
        </div>
        <div class="col-lg-12" style=" margin-top: 20px; margin-bottom: 10px;">
            <div class="card">
                <div class="card-header">
                    <h5>Acciones</h5>
                </div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-lg-6  col-md-6  col-sm-12" style="margin-bottom: 15px;">
                            <a href="@Url.Action("Index", "Production")" class="btn btn-success btn-lg btn-block" role="button" aria-pressed="true">
                                <div class="row">

                                    <div class="col-lg-12 text-right">
                                        <span style=" font-size: 12px;"> Acceso Directo </span>
                                        <h4 class="font-bold  text-center" style=" font-size: 19px !important; margin-bottom: 20px;">GENERAR PRODUCCION</h4>
                                    </div>
                                </div>
                            </a>
                        </div>
                        <div class="col-lg-6  col-md-6  col-sm-12" style="margin-bottom: 15px;">
                            <a href="@Url.Action("Index", "Informe")" class="btn btn-success btn-lg btn-block" role="button" aria-pressed="true">

                                <div class="row">

                                    <div class="col-lg-12 text-right">
                                        <span style=" font-size: 12px;"> Acceso Directo </span>
                                        <h4 class="font-bold  text-center" style=" font-size: 19px !important; margin-bottom: 20px;">PRODUCCION DIARIA</h4>
                                    </div>
                                </div>

                            </a>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

Geometrix_Consensus/Geometrix_Consensus/Views/Informe/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Geometrix_Consensus/Geometrix_Consensus/Views/Informe/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Geometrix_Consensus/Geometrix_Consensus/Views/Informe/Index.cshtml
@model IList<Geometrix_Consensus.Views.Models.SetFiguras>
@{
    ViewBag.Title = "Produccion Diaria";
}
<link href="css/bootstrap-datetimepicker.min.css" rel="stylesheet">
<script src="js/bootstrap-datetimepicker.min.js"></script>

<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-lg-12" style="margin-bottom:20px;">
            <div class="text-center m-t-lg">
                <h1 style="    font-size: 60px;">
                    @ViewData["SubTitle"]
                </h1>
            </div>
        </div>
        <div class="col-xl-12" style="margin-bottom:15px;">

        </div>
        <div class="col-xl-12">
            <div class="card" style="margin-bottom:15px;">
                <div class="card-header">
                    <div class="row">
                        <div class=" col-lg-6">
                            <h5 style="  margin-top: 7px;">Detalle de Set Generados</h5>
                        </div>
                        <div class=" col-lg-6" style="text-align:right;">
                            <a href="@Url.Action("Index", "Home")"><div class="btn btn-primary">Volver</div> </a>
                        </div>
                    </div>
                </div>
                <div class="card-body">
                    <table class="table">
                        <thead class="thead-dark">
                            <tr>
                                <th scope="col">#</th>
                                <th scope="col">Cuadrado</th>
                                <th scope="col">Rectangulo</th>
                                <th scope="col">Triangulo</th>
                                <th scope="col">Circulo</th>
                                <th scope="col">Valorizado Cuadrado</th>
                                <th scope="col">Valorizado Rectangulo</th>
                                <th scope="col">Valorizado Triangulo</th>
                                <th scope="col">Valorizado Circulo</th>
                                <th scope="col">Total Set</th>
                                @*<th scope="col">Handle</th>*@
                            </tr>
                        </thead>
                        <tbody>
                            @for (var i = 0; i < Model.Count; i++)
                            {
                                <tr>
                                    <td>
                                        @Html.DisplayFor(modelItem => Model[i].ID)
                                        @Html.HiddenFor(modelItem => Model[i].ID)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => Model[i].Cuadrado)
                                        @Html.HiddenFor(modelItem => Model[i].Cuadrado)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => Model[i].Rectangulo)
                                        @Html.HiddenFor(modelItem => Model[i].Rectangulo)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => Model[i].Triangulo)
                                        @Html.HiddenFor(modelItem => Model[i].Triangulo)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => Model[i].Circulo)
                                        @Html.HiddenFor(modelItem => Model[i].Circulo)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => Model[i].ValorizadoCuadrado)
                                        @Html.HiddenFor(modelItem => Model[i].ValorizadoCuadrado)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => Model[i].ValorizadoRectangulo)
                                        @Html.HiddenFor(modelItem => Model[i].ValorizadoRectangulo)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => Model[i].ValorizadoTriangulo)
                                        @Html.HiddenFor(modelItem => Model[i].ValorizadoTriangulo)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => Model[i].ValorizadoCiruculo)
                                        @Html.HiddenFor(modelItem => Model[i].ValorizadoCiruculo)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => Model[i].Total_Set)
                                        @Html.HiddenFor(modelItem => Model[i].Total_Set)
                                    </td>
                                </tr>
                            }

                        </tbody>
                    </table>
                
                </div>
            </div>
            <div class="card" style="margin-bottom:15px;">
                <div class="card-header">
                    <div class="row">
                        <div class=" col-lg-6">
                            <h5 style="  margin-top: 7px;">Produccion Diaria: </h5>
                        </div>
                    </div>
                </div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-xl-6">
                            <table class="table">
                                <thead class="thead-dark">
                                    <tr>

                                        <th scope="col">T.Cuadrado</th>
                                        <th scope="col">T.Rectangulo</th>
                                        <th scope="col">T.Triangulo</th>
                                        <th scope="col">T.Circulo</th>
                                        <th scope="col">T.Set</th>
                                        @*<th scope="col">Handle</th>*@
                                    </tr>
                                </thead>
                                <tbody>
                                 
                                    <tr>

                                        <td>
                                            <strong>@ViewBag.Cant_Cuadrado</strong>
                                        </td>
                                        <td>
                                            <strong>@ViewBag.Cant_Rectangulo</strong>
                                        </td>
                                        <td>
                                            <strong>@ViewBag.Cant_Triangulo</strong>
                                        </td>
                                        <td>
                                            <strong>@ViewBag.Cant_Circulo</strong>
                                        </td>
                                        <td>
                                            <strong>@ViewBag.Total_Cantidad_Set</strong>
                                        </td>
                                    </tr>
      

                                </tbody>
                            </table>
           
                        </div>
                        <div class="col-xl-6">
                            <dl class="dl-horizontal">

                                <dt>
                                    TOTAL COSTO
                                </dt>
                                <dd>
                                    $ @ViewBag.Total_Costo
                                </dd>

                                <dt>
                                    GANANCIA PERCIBIDA
                                </dt>
                                <dd>
                                    $ @ViewBag.Ganancia_Percibida
                                </dd>

                                <dt>
                                    PRECIO TOTAL:
                                </dt>
                                <dd>
                                    $ <strong style="color:forestgreen;">@ViewBag.Precio_Total</strong>
                                </dd>
                            </dl>
                        </div>
                    </div>
                  
                </div>
            </div>
        </div>
    </div>
</div>

Geometrix_Consensus/Geometrix_Consensus/Views/Production/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Geometrix_Consensus/Geometrix_Consensus/Views/Production/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Geometrix_Consensus/Geometrix_Consensus/Views/Production/Index.cshtml
@model IList<Geometrix_Consensus.Views.Models.Figuras>
@{
    ViewBag.Title = "Generar Produccion";
}
<link href="css/bootstrap-datetimepicker.min.css" rel="stylesheet">
<script src="js/bootstrap-datetimepicker.min.js"></script>

<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-lg-12"  style="margin-bottom:20px;">
            <div class="text-center m-t-lg">
                <h1 style="    font-size: 60px;">
                    @ViewData["SubTitle"]
                </h1>        
            </div>
        </div>
        <div class="col-xl-12" style="margin-bottom:15px;">
           
        </div>
        <div class="col-xl-12">
            @using (Html.BeginForm("AddProduction", "Production", new { enctype = "multipart/form-data" }))
            {
                @Html.AntiForgeryToken()
                <div class="card" style="margin-bottom:15px;">
                    <div class="card-header">
                        <div class="row">
                            <div class=" col-lg-6">
                                <h5 style="  margin-top: 7px;">Ingrese los datos Correspondientes</h5>
                            </div>
                            <div class=" col-lg-6" style="text-align:right;">
                                <a href="@Url.Action("Index", "Home")"><div class="btn btn-primary">Volver</div> </a>
                            </div>
                        </div>
                    </div>
                    <div class="card-body">
                        <div class="form-group row">
                            <label for="example-date-input" class="col-12 col-form-label">Fecha:</label>
                            <div class="col-12">
                                <input class="form-control" type="date" value="" id="example-date-input" name="example-date-input">
                            </div>
                        </div>
                    </div>
                </div>
                <div class="card">
                    <div class="card-header">
                        <div class="row">
                            <div class=" col-lg-6">
                                <h5 style="  margin-top: 7px;">Elegir Cantidades</h5>
                            </div>
                            <div class=" col-lg-6" style="text-align:right;">
                                <button type="submit" class="btn btn-primary btn-xl" style=" text-align:right;">
                                    Crear
                                </button>
                            </div>
                        </div>
                    </div>
                    <div class="card-body">
                        <table class="table">
                            <thead class="thead-dark">
                                <tr>
                                    <th scope="col">#</th>
                                    <th scope="col">Nombre</th>
                                    <th scope="col">Cantidad</th>
                                    @*<th scope="col">Handle</th>*@
                                </tr>
                            </thead>
                            <tbody>
                                @for (var i = 0; i < Model.Count; i++)
                                {
                                    <tr>
                                        <td>
                                            @Html.DisplayFor(modelItem => Model[i].ID)
                                            @Html.HiddenFor(modelItem => Model[i].ID)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => Model[i].Descripcion)
                                            @Html.HiddenFor(modelItem => Model[i].Descripcion)
                                        </td>
                                        <td>
                                            @Html.TextBoxFor(modelItem => Model[i].cantidad, new { @type = "number", @max = "999999", @min = "0", @maxlength = "6" })
                                            @Html.ValidationMessageFor(modelItem => Model[i].cantidad)
                                        </td>
                                    </tr>
                                }

                            </tbody>
                        </table>
                    </div>
                </div>
            }
        </div>
    </div>
</div>

Geometrix_Consensus/Geometrix_Consensus/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                @*<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>*@
                @*@Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })*@
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Camila Natalia Fein</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>